//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public int AccountId { get; set; }
        public string AccountHolderName { get; set; }
        public string AccountBalance { get; set; }
        public string AccountType { get; set; }
        public string MobileNumber { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    }
}
